In [1]:
# p.13 of Autograd
import torch
x = torch.tensor([1., 2.])
y = torch.tensor([4., 5.])
z = torch.tensor([7., 3.])
x.requires_grad

False

In [2]:
(x + y).requires_grad

False

In [8]:
z.requires_grad = True
print("{}, {}".format((x + z).requires_grad, z.dtype))

True, torch.float32


In [10]:
# p.13 of Autograd
# torch.autograd.grad
t = torch.tensor([1., 2., 4.]).requires_grad_()
u = torch.tensor([10., 20.]).requires_grad_()
a = t.pow(2).sum() + u.log().sum()
torch.autograd.grad(a, (t, u))

(tensor([2., 4., 8.]), tensor([0.1000, 0.0500]))

In [ ]:
import torch
a, b = torch.rand((2,2)), torch.rand((2,2))
print("a: {}\n, b: {} \n".format(a, b))

var1 = torch.sum(torch.abs((a * b)), 1)
print("L1 Distance is : ", var1)

var2 = torch.norm(((a * b)), 1, -1)
print("Torch NORM L1 Distance is : ", var2)

var3 = torch.sum(((a * b)) ** 2, 1).sqrt()
print("L2 SDistance is : ", var3)

var4 = torch.norm(((a * b)), 2, -1)
print("Torch NORM L2 Distance is : ", var4)

a: tensor([[0.6816, 0.0939],
        [0.3072, 0.3175]])
, b: tensor([[0.6887, 0.0302],
        [0.3534, 0.2138]]) 

L1 Distance is :  tensor([0.4723, 0.1764])
Torch NORM L1 Distance is :  tensor([0.4723, 0.1764])
L2 SDistance is :  tensor([0.4695, 0.1280])
Torch NORM L2 Distance is :  tensor([0.4695, 0.1280])


In [27]:
# p.16 of Autograd
# Tensor.backward()
x = torch.tensor([-3., 2., 5.]).requires_grad_()
u = x.pow(3).sum()
print(" x.grad:{}\n u.backward:{}\n x.grad:{}\n".format(x.grad, u.backward(), x.grad))


 x.grad:None
 u.backward:None
 x.grad:tensor([27., 12., 75.])



In [ ]:
# p.18 of Autograd
# Autograd machinery
w1 = torch.rand(5, 5).requires_grad_()
w2 = torch.rand(5, 5).requires_grad_()
x = torch.empty(5).normal_()
print("w1:{} \n w2: {} \n x : {}\n".format(w1, w2, x))

x0 = x
x1 = w1 @ x0
x2 = x0 + w2 @ x1
x3 = w1 @ (x1 + x2)

q = x3.norm()

q.backward()

In [43]:
# p.19 of Autograd
# Autograd machinery
x = torch.tensor([1.0, -2.0, 3.0, -4.0]).requires_grad_()
a = x.abs()
s = a.sum()
s

tensor(10., grad_fn=<SumBackward0>)

In [44]:
s.grad_fn.next_functions

((<AbsBackward at 0x7f2e4b6426d8>, 0),)

In [42]:
# p.21 of Autograd
# Autograd machinery
import torch

w1 = torch.rand(20, 10).requires_grad_()
b1 = torch.rand(20).requires_grad_()
w2 = torch.rand(5, 20).requires_grad_()
b2 = torch.rand(5).requires_grad_()
print('w1:{} \n, b1:{} \n, w2:{} \n, b2:{} \n'.format(w1, b1, w2, b2))

x = torch.rand(10)
h = torch.tanh(w1 @ x + b1)
y = torch.tanh(w2 @ h + b2)
print('x:{} \n, h:{} \n, y:{} \n'.format(x, h, y))

target = torch.rand(5)
loss = (y - target).pow(2).mean()
print('target: {}\n, loss: {}\n'.format( target, loss))

w1:tensor([[0.2057, 0.1120, 0.3829, 0.7853, 0.9681, 0.3197, 1.0000, 0.3131, 0.4090,
         0.1618],
        [0.0949, 0.1882, 0.5115, 0.9619, 0.6528, 0.8209, 0.6551, 0.8423, 0.4855,
         0.0661],
        [0.1498, 0.5130, 0.6390, 0.2275, 0.6803, 0.5407, 0.7196, 0.2352, 0.9339,
         0.9674],
        [0.5897, 0.1471, 0.0135, 0.5327, 0.1497, 0.4337, 0.7124, 0.3906, 0.3266,
         0.9996],
        [0.2840, 0.3949, 0.0254, 0.9276, 0.6352, 0.5418, 0.9800, 0.6053, 0.7550,
         0.5121],
        [0.2209, 0.2918, 0.1900, 0.5239, 0.7762, 0.8402, 0.2674, 0.5707, 0.1937,
         0.0828],
        [0.7663, 0.5325, 0.8117, 0.9017, 0.3651, 0.1186, 0.0074, 0.7106, 0.4857,
         0.6552],
        [0.9668, 0.7396, 0.2956, 0.0957, 0.9644, 0.4260, 0.1408, 0.2792, 0.6495,
         0.6851],
        [0.6365, 0.0928, 0.0324, 0.5978, 0.7010, 0.8284, 0.5317, 0.1794, 0.1734,
         0.8856],
        [0.0307, 0.9785, 0.6952, 0.8634, 0.9863, 0.8879, 0.2057, 0.6693, 0.7353,
         0.5982],
       

In [ ]:
# p.22 of Autograd
# Autograd machinery
w = torch.rand(3, 10, 10).requires_grad_()

def blah(k, x):
    for i in range(k):
        x = torch.tanh(w[i] @ x)
    return x

u = blah(1, torch.rand(10))
v = blah(3, torch.rand(10))
q = u.dot(v)
print('w: {} \n, u: {}\n, v: {}\n q: {}\n'.format(w, u, v, q))

w: tensor([[[0.8994, 0.2440, 0.1893, 0.6459, 0.5700, 0.9211, 0.2514, 0.0936,
          0.8225, 0.7140],
         [0.8251, 0.1572, 0.7071, 0.7246, 0.2332, 0.0252, 0.2717, 0.0095,
          0.3958, 0.8589],
         [0.4904, 0.7347, 0.5937, 0.8359, 0.7633, 0.9184, 0.0709, 0.2813,
          0.5969, 0.7658],
         [0.6238, 0.0499, 0.4602, 0.6955, 0.6587, 0.1786, 0.1717, 0.7216,
          0.9971, 0.2023],
         [0.5692, 0.5649, 0.7300, 0.8058, 0.1973, 0.5834, 0.1757, 0.3933,
          0.4887, 0.3248],
         [0.0969, 0.8534, 0.4092, 0.8902, 0.9609, 0.9601, 0.9526, 0.7646,
          0.8020, 0.5499],
         [0.3618, 0.0921, 0.0340, 0.7063, 0.2187, 0.2825, 0.7958, 0.3152,
          0.9216, 0.3837],
         [0.4946, 0.7579, 0.3342, 0.9217, 0.0402, 0.6776, 0.2853, 0.9225,
          0.1210, 0.4640],
         [0.3000, 0.4113, 0.0441, 0.6075, 0.0927, 0.7793, 0.3247, 0.4525,
          0.3716, 0.6748],
         [0.2985, 0.2954, 0.4066, 0.6649, 0.3951, 0.7282, 0.2323, 0.9887,
          0.06

In [ ]:
a = torch.tensor([1, 3])
b = torch.tensor([2, 2])
c = a.dot(b)
c

tensor(8)

In [ ]:
t = torch.tensor([1., 2., 4.]).requires_grad_()
u = torch.tensor([10., 20.]).requires_grad_()
a = t.pow(2).sum() + u.log().sum()
r = torch.autograd.grad(a, (t, u))
print("t:{} \n u:{} \n a:{} \n r = {} \n".format(t, u, a, r))

t:tensor([1., 2., 4.], requires_grad=True) 
 u:tensor([10., 20.], requires_grad=True) 
 a:26.298316955566406 
 r = (tensor([2., 4., 8.]), tensor([0.1000, 0.0500])) 



In [ ]:
s = u.log().sum()
torch.autograd.grad(s, u)

(tensor([0.1000, 0.0500]),)

In [ ]:
w = torch.rand(3, 10).requires_grad_()
x = torch.rand(10)
y = w @ x
print('w: {},\n x: {},\n y: {}'.format(w, x, y))

w: tensor([[0.3344, 0.1228, 0.1076, 0.0149, 0.5912, 0.4252, 0.1110, 0.9417, 0.8678,
         0.3534],
        [0.0811, 0.6673, 0.7601, 0.3127, 0.8452, 0.5921, 0.6898, 0.9130, 0.8685,
         0.5041],
        [0.7137, 0.7244, 0.7692, 0.6394, 0.4351, 0.3559, 0.5943, 0.6452, 0.5802,
         0.6465]], requires_grad=True),
 x: tensor([0.4765, 0.6922, 0.3652, 0.6364, 0.8267, 0.9203, 0.4900, 0.7421, 0.6845,
        0.9633]),
 y: tensor([2.8608, 4.3164, 4.0066], grad_fn=<MvBackward>)


In [ ]:
x = torch.tensor([1., 2., 2.]).requires_grad_()
q = x.norm()
q

tensor(3., grad_fn=<CopyBackwards>)

In [46]:
# p.24 of Autograd
# no_grad, detach
x = torch.rand(784)
w = torch.empty(10, 784).normal_(0, 1e-3).requires_grad_()
b = torch.empty(10).normal_(0, 1e-3).requires_grad_()
y = torch.rand(10)
eta = 0.01

for k in range(10001):
    y_hat = x @ w.t() + b
    loss = (y_hat - y).pow(2).mean()

    w.grad, b.grad = None, None
    loss.backward()

    with torch.no_grad():
        w -= eta * w.grad
        b -= eta * b.grad

In [47]:
# p.26 of Autograd
# no_grad, detach
a = torch.tensor( 0.5).requires_grad_()
b = torch.tensor(-0.5).requires_grad_()
for k in range(100):
    l = (a - 1)**2 + (b + 1)**2 + (a - b)**2
    ga, gb = torch.autograd.grad(l, (a, b))
    with torch.no_grad():
        a -= eta * ga
        b -= eta * gb
print('%.06f' % a.item(), '%.06f' % b.item())

0.333676 -0.333676


In [48]:
# p.27 of Autograd
# no_grad, detach
a = torch.tensor( 0.5).requires_grad_()
b = torch.tensor(-0.5).requires_grad_()
for k in range(100):
    l = (a - 1)**2 + (b + 1)**2 + (a.detach() - b)**2
    ga, gb = torch.autograd.grad(l, (a, b))
    with torch.no_grad():
        a -= eta * ga
        b -= eta * gb
print('%.06f' % a.item(), '%.06f' % b.item())

0.933690 -0.066310


In [49]:
# p.28 of Autograd
# create_graph = True
x = torch.tensor([1., 2., 3.]).requires_grad_()
phi = x.pow(2).sum()
g1, = torch.autograd.grad(phi, x, create_graph = True)
g1

tensor([2., 4., 6.], grad_fn=<MulBackward0>)

In [50]:
# p.28 of Autograd
# create_graph = True
psi = g1[0].exp() - g1[2].exp()
g2, = torch.autograd.grad(psi, x)
g2

tensor([  14.7781,    0.0000, -806.8576])

In [51]:
# p.29 of Autograd
x = torch.tensor([1., 2., 3.]).requires_grad_()
y = x.sin()
print('y : {}'.format(y))
l = y.sum()
l.backward()
print('l=sum(x.sin()), l : {}'.format(l))
y = x.sin()
y += 1
print('y : {}'.format(y))
l = y.sum()
l.backward()
print('l=sum(x.sin()+1), l : {}'.format(l))
y = x.sin()
y *=y
print('y : {}'.format(y))
l = y.sum()
print('l=sum(x.sin()*x.sin()), l : {}'.format(l))
l.backward()
print('l : {}'.format(l))

y : tensor([0.8415, 0.9093, 0.1411], grad_fn=<SinBackward>)
l=sum(x.sin()), l : 1.8918883800506592
y : tensor([1.8415, 1.9093, 1.1411], grad_fn=<AddBackward0>)
l=sum(x.sin()+1), l : 4.891888618469238
y : tensor([0.7081, 0.8268, 0.0199], grad_fn=<MulBackward0>)
l=sum(x.sin()*x.sin()), l : 1.5548100471496582


RuntimeError: ignored