In [1]:
import numpy as np

X = np.array([['Korea', 44, 7200],
              ['Japan', 27, 4800],
              ['China', 30, 6100]])

from sklearn.preprocessing import OneHotEncoder

onehotencoder = OneHotEncoder()

XX = onehotencoder.fit_transform(X[:, 0].reshape(-1, 1)).toarray()
print(XX)

X = np.delete(X, [0], axis=1) #0번째 열 삭제
X = np.concatenate((XX, X), axis = 1) # X와 XX를 붙인다
print(X)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
[['0.0' '0.0' '1.0' '44' '7200']
 ['0.0' '1.0' '0.0' '27' '4800']
 ['1.0' '0.0' '0.0' '30' '6100']]


In [2]:
class_vector = [2, 6, 6, 1]

from tensorflow.keras.utils import to_categorical
output = to_categorical(class_vector, num_classes = 7, dtype="int32")

print(output)

[[0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0]]
