In [1]:
# data preprocessing
# normalization & whitening

import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
pp_ecg_mean = pd.read_csv("./ECGdata/total_user_meanPerM_10cuts10mvs.csv")
pp_ecg_sdnn = pd.read_csv("./ECGdata/total_user_SDNNPerM_10cuts10mvs.csv")

print("dataShape : mean {}, sdnn {} ".format(pp_ecg_mean.shape, pp_ecg_sdnn.shape))


print("{}".format(pp_ecg_mean.isnull().sum()))

pp_ecg_mean['mean'] = pp_ecg_mean.mean(axis=1)

pp_ecg_mean_display = pp_ecg_mean.set_index(["0s", "mean"])#'10s', '20s', '30s','3670s', '3680s', 'mean'])
pp_ecg_mean_display.tail()

dataShape : mean (24, 369), sdnn (24, 369) 
0s       0
 10s     0
20s      1
30s      0
40s      0
50s      1
60s      0
70s      0
80s      0
90s      0
100s     0
110s     0
120s     0
130s     0
140s     0
150s     0
160s     0
170s     0
180s     0
190s     0
200s     0
210s     0
220s     0
230s     0
240s     0
250s     0
260s     0
270s     0
280s     0
290s     0
        ..
3390s    0
3400s    0
3410s    0
3420s    0
3430s    0
3440s    0
3450s    0
3460s    0
3470s    0
3480s    0
3490s    0
3500s    0
3510s    0
3520s    0
3530s    0
3540s    0
3550s    0
3560s    0
3570s    0
3580s    0
3590s    0
3600s    0
3610s    0
3620s    0
3630s    0
3640s    0
3650s    0
3660s    0
3670s    0
3680s    0
Length: 369, dtype: int64


10s        20s         30s        40s         50s  \
0s mean                                                                 
19 23.786983  49.450000        NaN    0.000000  44.916667   47.083333   
20 35.261524  40.153846  41.500000   54.000000  47.222222  111.750000   
21 29.405540  45.913043  46.416667   51.166667  38.636364         NaN   
22 23.616186  59.222222  56.200000  114.250000  61.222222   59.555556   
23 19.569284  37.500000  49.100000   53.090909  45.272727   39.000000   

                    60s        70s        80s        90s       100s  ...    \
0s mean                                                              ...     
19 23.786983  80.000000  40.500000  48.250000  42.230769  54.600000  ...     
20 35.261524  51.000000  62.833333  36.181818  42.000000  75.200000  ...     
21 29.405540   0.000000  58.100000  47.000000  50.250000  53.818182  ...     
22 23.616186  48.363636  49.500000  65.571429  46.818182  63.500000  ...     
23 19.569284  29.642857  35.312500  46.272727  44.538462  53.000000  ...     

              3590s  3600s  3610s  3620s  3630s  3640s  3650s  3660s  3670s  \
0s mean                                                                       
19 23.786983    0.0    0.0    0.0    0.0    0.0    0.0      0    0.0      0   
20 35.261524    0.0    0.0    0.0    0.0    0.0    0.0      0    0.0      0   
21 29.405540    0.0    0.0    0.0    0.0    0.0    0.0      0    0.0      0   
22 23.616186    0.0    0.0    0.0    0.0    0.0    0.0      0    0.0      0   
23 19.569284    0.0    0.0    0.0    0.0    0.0    0.0      0    0.0      0   

              3680s  
0s mean              
19 23.786983    0.0  
20 35.261524    0.0  
21 29.405540    0.0  
22 23.616186    0.0  
23 19.569284    0.0  

[5 rows x 368 columns]

In [39]:
pd.__version__

'0.23.0'

In [2]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pp_ecg_mean.isnull().sum()
#410s, 660s, 910s, 990s, 1000s, 1060s, 1290s, 1890s, 

0s       0
 10s     0
20s      1
30s      0
40s      0
50s      1
60s      0
70s      0
80s      0
90s      0
100s     0
110s     0
120s     0
130s     0
140s     0
150s     0
160s     0
170s     0
180s     0
190s     0
200s     0
210s     0
220s     0
230s     0
240s     0
250s     0
260s     0
270s     0
280s     0
290s     0
300s     0
310s     0
320s     0
330s     0
340s     0
350s     0
360s     0
370s     0
380s     0
390s     0
400s     0
410s     1
420s     0
430s     0
440s     0
450s     0
460s     0
470s     0
480s     0
490s     0
500s     0
510s     0
520s     0
530s     0
540s     0
550s     0
560s     0
570s     0
580s     0
590s     0
600s     0
610s     0
620s     0
630s     0
640s     0
650s     0
660s     1
670s     0
680s     0
690s     0
700s     0
710s     0
720s     0
730s     0
740s     0
750s     0
760s     0
770s     0
780s     0
790s     0
800s     0
810s     0
820s     0
830s     0
840s     0
850s     0
860s     0
870s     0
880s     0
890s     0
900s     0

In [ ]:
# replace ecg_mean
pp_ecg_mean['20s'] = pp_ecg_mean['20s'].replace(np.NaN, pp_ecg_mean.mean(axis=1))
pp_ecg_mean['50s'] = pp_ecg_mean['50s'].replace(np.NaN, pp_ecg_mean.mean(axis=1))
pp

In [3]:
# 20s, 50s, 410s, 660s, 910s, 990s, 1000s, 1060s, 1290s, 1890s, 
# replace ecg_mean
pp_ecg_mean['20s'] = pp_ecg_mean['20s'].replace(np.NaN, pp_ecg_mean.mean(axis=1))
pp_ecg_mean['50s'] = pp_ecg_mean['50s'].replace(np.NaN, pp_ecg_mean.mean(axis=1))
pp_ecg_mean['410s'] = pp_ecg_mean['410s'].replace(np.NaN, pp_ecg_mean.mean(axis=1))
pp_ecg_mean['660s'] = pp_ecg_mean['660s'].replace(np.NaN, pp_ecg_mean.mean(axis=1))
pp_ecg_mean['910s'] = pp_ecg_mean['910s'].replace(np.NaN, pp_ecg_mean.mean(axis=1))
pp_ecg_mean['990s'] = pp_ecg_mean['990s'].replace(np.NaN, pp_ecg_mean.mean(axis=1))
pp_ecg_mean['1000s'] = pp_ecg_mean['1000s'].replace(np.NaN, pp_ecg_mean.mean(axis=1))
pp_ecg_mean['1060s'] = pp_ecg_mean['1060s'].replace(np.NaN, pp_ecg_mean.mean(axis=1))
pp_ecg_mean['1290s'] = pp_ecg_mean['1290s'].replace(np.NaN, pp_ecg_mean.mean(axis=1))
pp_ecg_mean['1890s'] = pp_ecg_mean['1890s'].replace(np.NaN, pp_ecg_mean.mean(axis=1))

# replace ecg_sdnn
pp_ecg_sdnn['20s'] = pp_ecg_sdnn['20s'].replace(np.NaN, pp_ecg_sdnn.mean(axis=1))
pp_ecg_sdnn['50s'] = pp_ecg_sdnn['50s'].replace(np.NaN, pp_ecg_sdnn.mean(axis=1))
pp_ecg_sdnn['410s'] = pp_ecg_sdnn['410s'].replace(np.NaN, pp_ecg_sdnn.mean(axis=1))
pp_ecg_sdnn['660s'] = pp_ecg_sdnn['660s'].replace(np.NaN, pp_ecg_sdnn.mean(axis=1))
pp_ecg_sdnn['910s'] = pp_ecg_sdnn['910s'].replace(np.NaN, pp_ecg_sdnn.mean(axis=1))
pp_ecg_sdnn['990s'] = pp_ecg_sdnn['990s'].replace(np.NaN, pp_ecg_sdnn.mean(axis=1))
pp_ecg_sdnn['1000s'] = pp_ecg_sdnn['1000s'].replace(np.NaN, pp_ecg_sdnn.mean(axis=1))
pp_ecg_sdnn['1060s'] = pp_ecg_sdnn['1060s'].replace(np.NaN, pp_ecg_sdnn.mean(axis=1))
pp_ecg_sdnn['1290s'] = pp_ecg_sdnn['1290s'].replace(np.NaN, pp_ecg_sdnn.mean(axis=1))
pp_ecg_sdnn['1890s'] = pp_ecg_sdnn['1890s'].replace(np.NaN, pp_ecg_sdnn.mean(axis=1))

scaler = StandardScaler()
ecg_n_mean = scaler.fit_transform(pp_ecg_mean)
ecg_n_sdnn = scaler.fit_transform(pp_ecg_sdnn)

print("ecg_n_mean : {}".format(ecg_n_mean))
print("ecg_n_sdnn : {}".format(ecg_n_sdnn))

ecg_n_mean : [[-1.66132477 -0.3986698  -0.22810218 ... -0.20851441 -0.20851441
  -0.42114005]
 [-1.51686175 -0.17100391 -0.50476427 ... -0.20851441 -0.20851441
  -0.32382669]
 [-1.37239873 -0.64146906 -0.47364085 ... -0.20851441 -0.20851441
  -0.081368  ]
 ...
 [ 1.37239873 -0.44456884 -0.40671143 ... -0.20851441 -0.20851441
  -0.22573788]
 [ 1.51686175 -0.13912957 -0.10715819 ... -0.20851441 -0.20851441
  -0.38519064]
 [ 1.66132477 -0.63764413 -0.32455118 ... -0.20851441 -0.20851441
  -0.49665207]]
ecg_n_sdnn : [[-1.66132477 -1.08004515 -0.86052369 ... -0.20851441 -0.20851441
  -0.20851441]
 [-1.51686175  0.42743143 -0.26661438 ... -0.20851441 -0.20851441
  -0.20851441]
 [-1.37239873  0.3007492  -0.6057527  ... -0.20851441 -0.20851441
  -0.20851441]
 ...
 [ 1.37239873 -0.27572476 -0.86948889 ... -0.20851441 -0.20851441
  -0.20851441]
 [ 1.51686175 -0.77197774 -0.72154851 ... -0.20851441 -0.20851441
  -0.20851441]
 [ 1.66132477 -0.70232066  0.50256898 ... -0.20851441 -0.20851441
  -0.2

In [12]:


w_ecg_mean.shape

(22, 368)

In [4]:
from sklearn.cluster import KMeans
import math
import pickle
from mpl_toolkits.mplot3d import Axes3D
from numpy import genfromtxt
import matplotlib.pyplot as plt

w_ecg_mean = genfromtxt("./ECGdata/total_user_whitened_meanPerM_10scut10smv.csv", delimiter=',')
w_ecg_sdnn = genfromtxt("./ECGdata/total_user_whitened_SDNNPerM_10scut10smv.csv", delimiter=',')
w_ecg_lfhf = genfromtxt("./ECGdata/total_user_whitened_ratioLFHF_10scut10smv.csv", delimiter=',')

row_c = w_ecg_mean.shape[0]
col_c = w_ecg_mean.shape[1]

n = 3
size_X = (row_c) * (col_c)
X = [[ 0 for k in range(n)] for j in range(size_X)] 
for i in range(0, row_c):
    for j in range(0, col_c):
        n_comp = i*col_c+j
        X[n_comp][0] = w_ecg_mean[i,j]
        X[n_comp][1] = w_ecg_sdnn[i,j]
        X[n_comp][2] = w_ecg_lfhf[i,j]


n_clusters = 7
kmeans = KMeans(n_clusters, init='k-means++', n_init=10, max_iter=300, tol=1e4, 
                precompute_distances='auto', verbose=0, random_state=None, copy_x=True, n_jobs=1).fit(X[:][:])

print('{0}'.format(n_clusters))
print('kmeans labels:({0})\n{1}'.format(kmeans.labels_.shape, kmeans.labels_))
print('kmeans centers:{0}'.format(kmeans.cluster_centers_))
print('kmeans intertia_:{0}'.format(kmeans.inertia_))

#Draw Picture for the clustered data Set
estimators = {'k_means_ECG_3': kmeans}
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

n = 792
xs = w_ecg_mean
ys = w_ecg_sdnn
zs = w_ecg_lfhf

ax.set_xlabel('mean RtoR')
ax.set_ylabel('SDNN')
ax.set_zlabel('LF/HF')

ax.scatter(xs, ys, zs, c=kmeans.labels_, cmap='viridis')
plt.show()


7
kmeans labels:((8096,))
[5 3 5 ... 2 2 2]
kmeans centers:[[ 0.66319398  0.54163458  2.16619933]
 [ 0.49506634  0.29558723  0.3643547 ]
 [ 0.92195677  0.73156047  0.79523117]
 [ 3.31301183 12.1313465   5.826764  ]
 [ 2.10157116  5.51135781  1.15124308]
 [ 1.41411546  1.45007996  0.68311003]
 [ 0.68241262  1.43512357  6.54962145]]
kmeans intertia_:3022.319119694395


<Figure size 640x480 with 1 Axes>